package dev.handheld.launcher.audio

import dev.handheld.launcher.contract.SemanticInputAction

/** Durations match the original PCM assets generated by Generate-ControllerSounds.ps1. */
internal enum class ControllerSoundCue(val durationMillis: Long) {
    MOVE(62), SELECT(94), CONFIRM(132), BACK(110), PAGE(96), FILTER(72),
}

/** Acknowledges the input engine's handled actions, never raw key/axis reports or touch. */
internal class ControllerSoundPolicy(
    private val enabled: () -> Boolean,
    private val mediaAudible: () -> Boolean,
    private val monotonicTimeMillis: () -> Long = { System.nanoTime() / 1_000_000L },
    private val play: (ControllerSoundCue) -> Boolean,
) {
    private var active = false
    private var busyUntilMillis = Long.MIN_VALUE
    private var dispatching: SemanticInputAction? = null
    private var selectionExpected = false

    fun setActive(value: Boolean) { active = value; if (!value) stop() }

    fun stop() { busyUntilMillis = Long.MIN_VALUE }

    /** Called synchronously by a handled card-navigation branch before deferred focus work. */
    fun expectItemSelection() {
        if (dispatching?.canSelectItem() == true) selectionExpected = true
    }

    /** The UI calls this only for a changed, controller-driven card selection. */
    fun onItemSelected(): Boolean {
        expectItemSelection()
        return emit(ControllerSoundCue.SELECT)
    }

    fun dispatch(action: SemanticInputAction, handle: (SemanticInputAction) -> Boolean): Boolean {
        val previousAction = dispatching
        val previousExpected = selectionExpected
        dispatching = action
        selectionExpected = false
        try {
            val handled = handle(action)
            if (handled && !(selectionExpected && action.canSelectItem())) emit(action.cue())
            return handled
        } finally {
            dispatching = previousAction
            selectionExpected = previousExpected
        }
    }

    private fun emit(cue: ControllerSoundCue): Boolean {
        if (!active || !enabled()) return false
        val now = monotonicTimeMillis()
        if (now < busyUntilMillis) return false
        if (!mediaAudible()) return false
        // SoundPool has no completion callback. Known PCM duration plus a small render
        // margin bounds the single voice. Busy or unloaded events are dropped, never queued.
        val started = try { play(cue) } catch (_: RuntimeException) { false }
        if (started) busyUntilMillis = now + cue.durationMillis + PLAYBACK_MARGIN_MILLIS
        return started
    }

    private fun SemanticInputAction.canSelectItem(): Boolean = when (this) {
        SemanticInputAction.NAVIGATE_UP, SemanticInputAction.NAVIGATE_DOWN,
        SemanticInputAction.NAVIGATE_LEFT, SemanticInputAction.NAVIGATE_RIGHT,
        SemanticInputAction.PREVIOUS_FILTER, SemanticInputAction.NEXT_FILTER -> true
        else -> false
    }

    private fun SemanticInputAction.cue(): ControllerSoundCue = when (this) {
        SemanticInputAction.NAVIGATE_UP, SemanticInputAction.NAVIGATE_DOWN,
        SemanticInputAction.NAVIGATE_LEFT, SemanticInputAction.NAVIGATE_RIGHT -> ControllerSoundCue.MOVE
        SemanticInputAction.CONFIRM -> ControllerSoundCue.CONFIRM
        SemanticInputAction.BACK -> ControllerSoundCue.BACK
        SemanticInputAction.PREVIOUS_DESTINATION, SemanticInputAction.NEXT_DESTINATION,
        SemanticInputAction.SECONDARY, SemanticInputAction.TERTIARY,
        SemanticInputAction.MENU -> ControllerSoundCue.PAGE
        SemanticInputAction.PREVIOUS_FILTER, SemanticInputAction.NEXT_FILTER -> ControllerSoundCue.FILTER
    }

    private companion object { const val PLAYBACK_MARGIN_MILLIS = 16L }
}
