package dev.handheld.launcher.audio

import dev.handheld.launcher.contract.SemanticInputAction

/** Durations match the original PCM assets generated by Generate-ControllerSounds.ps1. */
internal enum class ControllerSoundCue(val durationMillis: Long) {
    MOVE(38), SELECT(48), CONFIRM(72), BACK(60), PAGE(56), FILTER(40);

    // The restored 48 ms selection pop must finish before the 55 ms repeat.
    // A 16 ms navigation margin would abruptly halve its audible rate.
    val minimumIntervalMillis: Long
        get() = if (this == MOVE || this == SELECT)
            maxOf(ControllerSoundLoudness.MINIMUM_START_INTERVAL_MILLIS, durationMillis + 2L)
        else maxOf(80L, durationMillis + 16L)
}

/** Sound cadence and duplicate-selection suppression. Haptic bursts have a separate owner. */
internal class ControllerSoundPolicy(
    private val enabled: () -> Boolean,
    private val mediaAudible: () -> Boolean,
    private val monotonicTimeMillis: () -> Long = { System.nanoTime() / 1_000_000L },
    private val play: (ControllerSoundCue) -> Boolean,
) {
    private var active = false
    private var busyUntilMillis = Long.MIN_VALUE
    private var dispatching: SemanticInputAction? = null
    private var selectionExpected = false

    fun onTouchActivation(): Boolean = emit(ControllerSoundCue.CONFIRM)

    fun setActive(value: Boolean) { active = value; if (!value) stop() }

    fun stop() { busyUntilMillis = Long.MIN_VALUE }

    /** Called synchronously by a handled card-navigation branch before deferred focus work. */
    fun expectItemSelection() {
        if (dispatching?.canSelectItem() == true) selectionExpected = true
    }

    /** The UI calls this only for a changed, controller-driven card selection. */
    fun onItemSelected(): Boolean {
        expectItemSelection()
        return emit(ControllerSoundCue.SELECT)
    }

    fun dispatch(action: SemanticInputAction, handle: (SemanticInputAction) -> Boolean): Boolean {
        val previousAction = dispatching
        val previousExpected = selectionExpected
        dispatching = action
        selectionExpected = false
        try {
            val handled = handle(action)
            if (handled && !(selectionExpected && action.canSelectItem())) emit(action.feedbackCue())
            return handled
        } finally {
            dispatching = previousAction
            selectionExpected = previousExpected
        }
    }

    private fun emit(cue: ControllerSoundCue): Boolean {
        if (!active) return false
        val now = monotonicTimeMillis()
        if (now < busyUntilMillis) return false
        // SoundPool has no completion callback. Known PCM duration plus a small render
        // margin bounds the single voice. Busy or unloaded events are dropped, never queued.
        val started = try { enabled() && mediaAudible() && play(cue) } catch (_: RuntimeException) { false }
        // Native calls can be slow on handheld audio drivers. Their execution time must
        // not consume the guard and admit a second cue as soon as this call returns.
        if (started) busyUntilMillis = monotonicTimeMillis() + cue.minimumIntervalMillis
        return started
    }

    private fun SemanticInputAction.canSelectItem(): Boolean = when (this) {
        SemanticInputAction.NAVIGATE_UP, SemanticInputAction.NAVIGATE_DOWN,
        SemanticInputAction.NAVIGATE_LEFT, SemanticInputAction.NAVIGATE_RIGHT,
        SemanticInputAction.PREVIOUS_FILTER, SemanticInputAction.NEXT_FILTER -> true
        else -> false
    }

}

internal fun SemanticInputAction.feedbackCue(): ControllerSoundCue = when (this) {
        SemanticInputAction.NAVIGATE_UP, SemanticInputAction.NAVIGATE_DOWN,
        SemanticInputAction.NAVIGATE_LEFT, SemanticInputAction.NAVIGATE_RIGHT -> ControllerSoundCue.MOVE
        SemanticInputAction.CONFIRM -> ControllerSoundCue.CONFIRM
        SemanticInputAction.BACK -> ControllerSoundCue.BACK
        SemanticInputAction.PREVIOUS_DESTINATION, SemanticInputAction.NEXT_DESTINATION,
        SemanticInputAction.SECONDARY, SemanticInputAction.TERTIARY, SemanticInputAction.ITEM_DETAILS,
        SemanticInputAction.MENU -> ControllerSoundCue.PAGE
        SemanticInputAction.PREVIOUS_FILTER, SemanticInputAction.NEXT_FILTER -> ControllerSoundCue.FILTER
}
